config/routes.rb
Rails.application.routes.draw do
  resources :propperties
  devise_for :accounts
  root :to => 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  has_many :propperties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/propperty.rb
class Propperty < ApplicationRecord
  belong_to :account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/propperties_controller.rb
class ProppertiesController < ApplicationController
  before_action :set_propperty, only: [:show, :edit, :update, :destroy]

  # GET /propperties
  # GET /propperties.json
  def index
    @propperties = Propperty.all
  end

  # GET /propperties/1
  # GET /propperties/1.json
  def show
  end

  # GET /propperties/new
  def new
    @propperty = Propperty.new
  end

  # GET /propperties/1/edit
  def edit
  end

  # POST /propperties
  # POST /propperties.json
  def create
    @propperty = Propperty.new(propperty_params)

    respond_to do |format|
      if @propperty.save
        format.html { redirect_to @propperty, notice: 'Propperty was successfully created.' }
        format.json { render :show, status: :created, location: @propperty }
      else
        format.html { render :new }
        format.json { render json: @propperty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /propperties/1
  # PATCH/PUT /propperties/1.json
  def update
    respond_to do |format|
      if @propperty.update(propperty_params)
        format.html { redirect_to @propperty, notice: 'Propperty was successfully updated.' }
        format.json { render :show, status: :ok, location: @propperty }
      else
        format.html { render :edit }
        format.json { render json: @propperty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /propperties/1
  # DELETE /propperties/1.json
  def destroy
    @propperty.destroy
    respond_to do |format|
      format.html { redirect_to propperties_url, notice: 'Propperty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_propperty
      @propperty = Propperty.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def propperty_params
      params.require(:propperty).permit(:name, :address, :price, :rooms, :bathrooms)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/propperties_helper.rb
module ProppertiesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/_footer.html.erb
<footer class="container">
  <p>Scopy: Property Finder 2019</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <header>
    <%= render "layouts/nav/public" %>
  </header>
    <!-- se aplica los carteles de adevertencia de devise -->
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    <%= yield %>

    <%= render "layouts/footer" %>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Latest</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      <li class="nav-item">
        <%= link_to "Log Out", new_account_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/propperties/_form.html.erb
<%= form_with(model: propperty, local: true) do |form| %>
  <% if propperty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(propperty.errors.count, "error") %> prohibited this propperty from being saved:</h2>

      <ul>
        <% propperty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :rooms %>
    <%= form.number_field :rooms %>
  </div>

  <div class="field">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/propperties/edit.html.erb
<h1>Editing Propperty</h1>

<%= render 'form', propperty: @propperty %>

<%= link_to 'Show', @propperty %> |
<%= link_to 'Back', propperties_path %>

app/views/propperties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Propperties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @propperties.each do |propperty| %>
      <tr>
        <td><%= propperty.name %></td>
        <td><%= propperty.address %></td>
        <td><%= propperty.price %></td>
        <td><%= propperty.rooms %></td>
        <td><%= propperty.bathrooms %></td>
        <td><%= link_to 'Show', propperty %></td>
        <td><%= link_to 'Edit', edit_propperty_path(propperty) %></td>
        <td><%= link_to 'Destroy', propperty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Propperty', new_propperty_path %>

app/views/propperties/new.html.erb
<h1>New Propperty</h1>

<%= render 'form', propperty: @propperty %>

<%= link_to 'Back', propperties_path %>

app/views/propperties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @propperty.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @propperty.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @propperty.price %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @propperty.rooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @propperty.bathrooms %>
</p>

<%= link_to 'Edit', edit_propperty_path(@propperty) %> |
<%= link_to 'Back', propperties_path %>